### ISSUE TITLE
vagrant ユーザーにsudo権限がない

### ISSUE THREAD

**Issue by dandan611** [dandan611/Settler#12]

**Comment by dandan611** [comment]
ひとまずyml化
```
- name: create docker group
  group: 
    name: docker
    state: present
  become: yes

- name: create docker group
  user: 
    name: vagrant
    state: present
  become: yes
```
