### ISSUE TITLE
GitLab Runnerを入れる

### ISSUE THREAD

**Issue by dandan611** [dandan611/Settler#33]
対象は、devmng

**Comment by dandan611** [comment]
モジュールは気にせず、ひとまずyml化

```
- name: download gitlab-runner-linux-amd64
  shell: |
    wget -O /usr/local/bin/gitlab-runner https://gitlab-runner-downloads.s3.amazonaws.com/latest/binaries/gitlab-runner-linux-amd64
  become: yes

- name: install gitlab-runner-linux-amd64
  shell: |
    chmod +x /usr/local/bin/gitlab-runner
    useradd --comment 'GitLab Runner' --create-home gitlab-runner --shell /bin/bash
    /usr/local/bin/gitlab-runner install --user=gitlab-runner --working-directory=/home/gitlab-runner
  become: yes

- name: install docker
  yum:
    name:
      - docker
    state: present
  become: yes

- name: restart gitlab-runner service
  systemd:
    name: gitlab-runner
    state: restarted
    enabled: yes
  become: yes
```
